# A biblioteca *NumPy*

## Introdução

Neste capítulo abordamos alguma  funcionalidades da biblioteca *NumPy*, nomeadamente:
- a criação de vetores e de matrizes,
- a manipulação de matrizes,
- as operações elementares com matrizes,
- a geração de números aleatórios.


## Objetivos de aprendizagem

No final deste capítulo deveremos ser capazes de usar as seguintes funcionalidades da biblioteca *NumPy*:
- criar vetores e matrizes,
- manipular matrizes usando a indexação, *slicing*, etc.,
- aplicar as operações elementares em matrizes,
- aplicar as *ufuncs* nativas e
- gerar números aleatórios de acordo com as distribuições de probabilidade Uniforme, Gaussiana e de Poisson.



## Generalidades

Para usarmos esta biblioteca é necessário a sua importação para o espaço de trabalho,

In [1]:
import numpy as np


Além de importarmos a biblioteca `numpy` também lhe atribuímos o nome `np` através do qual podemos invocar os métodos, ou seja, para um determinado *método* existente, a instrução `np.método()` é equivalente a `numpy.método()`.


## Criação de vetores e matrizes

Para criarmos vetores e matrizes usamos o método `array` juntamente com listas ou tuplos. Por exemplo, para criamos o vetor (ou matriz) $[0\, 1\,  2\, 3]$ podemos executar,

In [2]:
# Criação de uma matriz com np.array() e uma lista
a = np.array([0, 1, 2, 3])

print(a)


[0 1 2 3]


ou, em alternativa,

In [3]:
# Criação de uma matriz com np.array() e um tuplo
a = np.array((0, 1, 2, 3))

print(a)


[0 1 2 3]


Os objetos que representam as matrizes criadas através do método `array` são do tipo `ndarray`.

In [4]:
type(a)


numpy.ndarray

Outra maneira de gerar esta matriz é através do método `arange(inicio, fim+1, intervalo)`,

In [5]:
a = np.arange(0, 4, 1)
print(a)


[0 1 2 3]


Podemos criar matrizes com várias dimensões. Por exemplo, para criarmos a seguinte matriz com duas linhas e três colunas,

$\left[\begin{array}{ccc}
   0 & 1 & 2\\
   3 & 4 & 5
\end{array}\right]$

podemos usar o método `array` especificando as duas linhas da matriz,

In [6]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])
print(b)


[[0 1 2]
 [3 4 5]]


Para criarmos uma matriz com três dimensões, especificamos as fatias (*slices*) as quais por, suas vez, devem especificar as linhas da matriz. No exemplo seguinte a matriz `c` tem 4 fatias, duas linhas (por fatia) e 3 colunas (por linha),

In [7]:
c = np.array([[[1, 2, 3], [1, 3, 2]], [[2, 2, 1], [2, 1, 2]],
              [[3, 1, 3], [3, 4, 2]], [[4, 5, 6], [4, 7, 6]]])

print(c)


[[[1 2 3]
  [1 3 2]]

 [[2 2 1]
  [2 1 2]]

 [[3 1 3]
  [3 4 2]]

 [[4 5 6]
  [4 7 6]]]



<img src="./figures/matrizes_nd.png" alt="Exemplos de matrizes" style="height: 350px;"/>

### Dimensão

Em Python, podemos interpretar a dimensão de uma matriz como o número correspondente de índices. Para determinarmos esta dimensão usamos o método `ndim` que devolve um inteiro com esta informação,

In [8]:
print('Dimensão da matriz \'a\': ', a.ndim)
print('Dimensão da matriz \'b\': ', b.ndim)
print('Dimensão da matriz \'c\': ', c.ndim)


Dimensão da matriz 'a':  1
Dimensão da matriz 'b':  2
Dimensão da matriz 'c':  3


Para determinarmos o número de elementos de uma matriz em cada uma das suas dimensões usamos o método `shape` que devolve um tuplo com esta informação. Por exemplo,

In [9]:
print(a.shape)
n_colunas_de_a = a.shape[0]
print('A matriz \'{}\' tem {} colunas.'.format('a', n_colunas_de_a))


(4,)
A matriz 'a' tem 4 colunas.


In [10]:
print(b.shape)
n_linhas_de_b = b.shape[0]
n_colunas_de_b = b.shape[1]

print('A matriz \'{}\' tem {} linhas e {} colunas.'.format(
    'b', n_linhas_de_b, n_colunas_de_b))


(2, 3)
A matriz 'b' tem 2 linhas e 3 colunas.


In [11]:
print(c.shape)
n_fatias_de_c = c.shape[0]
n_linhas_de_c = c.shape[1]
n_colunas_de_c = c.shape[2]

print('A matriz \'{}\' tem {} fatias, {} linhas \
e {} colunas.'.format('c', n_fatias_de_c, n_linhas_de_c, n_colunas_de_c))


(4, 2, 3)
A matriz 'c' tem 4 fatias, 2 linhas e 3 colunas.


## Indexação

A indexação permite-nos aceder aos elementos individuais de uma matriz e segue a ordenação devolvida pelo método `shape`. Assim, para uma matriz de dimensão unitária o acesso aos seu elementos individuais é feito indexando cada uma das suas colunas. Por exemplo, para a matriz 'a' a indexação é  efetuada da seguinte forma,

In [12]:
print(a[0], end='; ')  # elemento da primeiracoluna,
print(a[1], end='; ')  # elemento da segunda coluna,
print(a[2], end='; ')  # elemento da terceira coluna,
print(a[3], end=' ')  # elemento da quarta coluna.


0; 1; 2; 3 


Tal como para a indexação de *strings*, listas ou tuplos, a primeiro índice é o 0 e o último é $n-1$, em que $n$ representa número de elemento na dimensão considerada. 


Para a matriz `b` com duas dimensões esta indexação é efetuada genericamente `b[linha,coluna]`,

In [13]:
print(b[0, 0], end='; ')  # elemento da primeira linha, primeira coluna
print(b[0, 1], end='; ')  # elemento da primeira linha, segunda coluna
print(b[0, 2], end='; ')  # elemento da primeira linha, terceira coluna
print(b[1, 0], end='; ')  # elemento da segunda linha, primeira coluna
print(b[1, 1], end='; ')  # elemento da segunda linha, segunda coluna
print(b[1, 2], end='  ')  # elemento da segunda linha, terceira coluna


0; 1; 2; 3; 4; 5  

Para a matriz `c` com três dimensões esta indexação é efetuada genericamente `c[fatia,linha,coluna]`. Por exemplo,

In [14]:
fatia, linha, coluna = 1, 0, 2
print('Matriz C: elemento da fatia {}, linha {}, \
coluna {}: {}'. format(fatia, linha, coluna, c[fatia, linha, coluna]))


Matriz C: elemento da fatia 1, linha 0, coluna 2: 1


Além de consultarmos os elementos da matriz, também é possível a sua modificação. Por exemplo,

In [15]:
b[0, 0] = 4
b[1, 0] = 9
print(b)


[[4 1 2]
 [9 4 5]]


Dependendo da dimensão da matriz, é possível também indexar linhas e colunas de forma individual. Por exemplo, para acedermos à primeira linha da matriz `b` executamos,

In [16]:
b[0]


array([4, 1, 2])

Para indexar a segunda coluna da matriz `b` executamos,

In [17]:
b[:, 1]


array([1, 4])

Para acedermos à primeira fatia da matriz `c` executamos,

In [18]:
c[0]


array([[1, 2, 3],
       [1, 3, 2]])

Para acedermos à primeira linha da primeira fatia da matriz `c` executamos,

In [19]:
c[0, 0]


array([1, 2, 3])

Para acedermos à segunda coluna da quarta fatia da matriz `c` executamos,

In [20]:
c[3, :, 1]


array([5, 7])

## *Slicing*
Esta operação permite-nos aceder aos elementos de uma matriz especificando uma sequência para os seu índices com o formato `[inicio:fim+1]` ou `[inicio:fim+1:intervalo]`. Por exemplo,

In [21]:
a = np.arange(15)
print('matriz a =', a)
b = a[2:11:3]
print('matriz b =', b)


matriz a = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
matriz b = [2 5 8]


In [22]:
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('matriz c =', c)
d = c[0:2, 1:4]
print('matriz d =', d)


matriz c = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
matriz d = [[2 3 4]
 [7 8 9]]


## Cópia de matrizes

A cópia de matrizes obedece às mesmas considerações que devemos ter em conta quando copiamos listas. Se quisermos duas entidades diferentes devemos usar o método `copy`,

In [23]:
c = np.array([1, 2, 3, 4, 5])
d = c
e = c.copy()

d[0] = 20

print('matriz c =', c)
print('matriz d =', d)
print('matriz e =', e)


matriz c = [20  2  3  4  5]
matriz d = [20  2  3  4  5]
matriz e = [1 2 3 4 5]


## Redimensionamento
Para redimensionarmos uma matriz podemos usar o método `reshape`. Por exemplo,

In [24]:
a = np.arange(1, 12, 2)
b = a.reshape(2, 3)
print('matriz a =', a)
print('matriz b =', b)


matriz a = [ 1  3  5  7  9 11]
matriz b = [[ 1  3  5]
 [ 7  9 11]]


Podemos transformar uma matriz de dimensão superior numa matriz de dimensão unitária, 

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(-1)
print('matriz a =', a)
print('matriz b =', b)


matriz a = [[1 2 3]
 [4 5 6]]
matriz b = [1 2 3 4 5 6]


## Iteração dos elementos

Os seguintes exemplos ilustram como podemos aceder aos elementos de uma matriz através da iteração com ciclos `for`,  

In [26]:
a = np.array([1, 2, 3])
for elemento in a:
    print(elemento, end=' ')


1 2 3 

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
for linhas in a:
    print(linhas)


[1 2 3]
[4 5 6]


In [28]:
for linhas in a:
    for elemento in linhas:
        print(elemento, end=' ')


1 2 3 4 5 6 

O método `nditer` permite iterações mais avançadas. Por exemplo,

In [29]:
for elemento in np.nditer(a):
    print(elemento, end=' ')


1 2 3 4 5 6 

## Casos Particulares

Consideramos agora os métodos nativos para a criação de casos particulares de matrizes: a matriz *all-ones*, a matriz nula, a matriz identidade e a matriz diagonal.

### A matriz *all-ones* 

Neste tipo de matriz todos os seu elementos são iguais a 1. Para gerarmos uma matriz deste género podemos usar o método `ones`. Por exemplo, para gerar uma destas matrizes com $m$ linhas e $n$ colunas,

In [30]:
m, n = 3, 4
a = np.ones((m, n))
a


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### A matriz nula
Para gerarmos uma matriz nula podemos usar o método `zeros`. Por exemplo, para gerar uma matriz nula com $m$ linhas e $n$ colunas,

In [31]:
m, n = 3, 4
b = np.zeros((m, n))
b


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### A matriz identidade
Para gerarmos uma matriz identidade podemos recorrer ao método `eye`. A sua criação pode ser com números inteiros ou reais (`float`) através da opção `dtype`. Por exemplo, para criarmos uma destas matrizes com $n$ linhas e $n$ colunas,

In [32]:
n = 3
c = np.eye(n, dtype=int)
c


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
c = np.eye(n, dtype=float)
c


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### A matriz diagonal
Para gerarmos uma matriz diagonal podemos usar o método `diag` juntamente com uma lista ou um tuplo que contém os elemento da diagonal. O comprimento desta lista ou tuplo determina a dimensão da matriz. 

Por exemplo:

In [34]:
d = np.diag(np.array([1, 2, 3, 4]))
d


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
d = np.diag(np.array((1, 2, 3, 4)))
d


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Operações elementares

### Soma e diferença
Em relação a estas operações podemos considerar duas situações:
+ a soma ou diferença de um escalar com uma matriz,
+ a soma ou diferença de matrizes.

Consideremos as matrizes `a` e `b`,

In [36]:
a = np.array(10 * np.arange(4))
print(a)


[ 0 10 20 30]


In [37]:
b = np.arange(4)
print(b)


[0 1 2 3]


A adição e a subtração de um escalar a uma matriz é efetuada usando os operadores $+$ e $-$, respetivamente. Por exemplo,

In [38]:
a1 = a + 5
print(a1)


[ 5 15 25 35]


A soma e diferença de matrizes é efetuada usando os operadores $+$ e $-$, respetivamente. Por exemplo,

In [39]:
c = a-b
print(c)


[ 0  9 18 27]


In [40]:
d = a+b
print(d)


[ 0 11 22 33]


### Multiplicação
Em relação ao produto há que considerar três situações:
+ o produto de um escalar com uma matriz
+ o produto elemento a elemento: $a(m,n)\times b(m,n)$
+ o produto matricial

Consideremos as matrizes `a` e `b`,

In [41]:
a = np.array([[1, 1],
              [0, 1]])
b = np.array([[2, 1],
              [3, 4]])


Para o produto de um escalar com uma matriz usamos o operador $*$,

In [42]:
print(100*a)


[[100 100]
 [  0 100]]


Para o produto elemento-a-elemento também usamos o operador $*$,

In [43]:
c = a * b
print(c)


[[2 1]
 [0 4]]


Para o produto matricial usamos o operador `@` ou o {index}`método<dot>` `dot`,

In [44]:
d = a @ b
print(d)


[[5 5]
 [3 4]]


In [45]:
d = a.dot(b)
print(d)


[[5 5]
 [3 4]]


### Divisão

A divisão de matrizes elemento-a elemento, pode ser efetuada com o operador $/$,

In [46]:
a/b


array([[0.5 , 1.  ],
       [0.  , 0.25]])

### Divisão inteira

A divisão inteira de matrizes elemento-a elemento, pode ser efetuada com o operador $//$,

In [47]:
a//b


array([[0, 1],
       [0, 0]])

### Resto da divisão inteira

O resto da divisão inteira de matrizes elemento-a elemento, pode ser efetuada com o operador $\%$,

In [48]:
a % b


array([[1, 0],
       [0, 1]])

### Transposta
Para calcularmos a transposta de uma matriz usamos o método `transpose`,

In [49]:
c_t = np.transpose(c)
print(c_t)


[[2 0]
 [1 4]]


ou, em alternativa,

In [50]:
c_t = c.T
print(c_t)


[[2 0]
 [1 4]]


Este método também é útil para criamos um vetor no formato coluna,

In [51]:
v_l = np.array([[1, 2, 3, 4, 5]])
v_c = v_l.T
print('vector linha=', v_l)
print('vector coluna=\n', v_c)


vector linha= [[1 2 3 4 5]]
vector coluna=
 [[1]
 [2]
 [3]
 [4]
 [5]]


### Exponenciação

O operador $**$ é usado para a exponenciação dos elementos individuais da matriz. O expoente pode ser um escalar ou uma matriz

In [52]:
e = d**2
print('matriz e:', e)

f = d ** np.array([[2, 2], [2, 2]])
print('matriz f:', f)


matriz e: [[25 25]
 [ 9 16]]
matriz f: [[25 25]
 [ 9 16]]


### Determinante
Para calcularmos determinantes de matrizes podemos usar o método `linalg.det`,

In [53]:
det_d = np.linalg.det(d)
print('Determinante de \'{0}\': {1:1.1f}'.format('d', det_d))


Determinante de 'd': 5.0


### Documentação e ajuda

A documentação sobre matrizes pode ser acedida usado a função `help`,

In [54]:
# Remova os comentários para aceder à documentação
# help (np.array)
# np.lookfor('create array')


## Funções universais (*ufunc*)
As funções universais  - *universal functions (ufunc)* - operam sobre a forma matricial do *NumPy*, ou seja sobre os objetos do tipo `ndarray`. Estas funções implementam formas de vetorização que são mais rápidas do que a sua correspondente forma iterativa. 

As *ufuncs* contemplam funções aritméticas, trigonométricas, logaritmos, etc. É possível implementarmos *ufuncs* de acordo com a necessidade da solução em questão.

### Operações Aritméticas

As *ufuncs* para a aritmética simples sobre matrizes produzem resultados semelhantes aos operadores acima mencionados:
+ `add(a,b)` : semelhante ao operador $+$; devolve uma matriz com a soma (elemento a elemento) das matrizes `a` e `b`,
+ `subtract(a,b)` : semelhante ao operador $-$; devolve uma matriz com a diferença (elemento a elemento) das matrizes `a` e `b`,
+ `multiply(a,b)` : semelhante ao operador $*$; devolve uma matriz com a multiplicação (elemento a elemento) das matrizes `a` e `b`,
+ `divide(a,b)` : semelhante ao operador $/$; devolve uma matriz com a divisão (elemento a elemento) das matrizes `a` e `b`,
+ `power(a,b)` : semelhante ao operador $**$; devolve uma matriz com a potenciação (elemento a elemento) das matrizes `a` e `b`.

Exemplos:

In [55]:
a = np.array([[2, 4], [9, 6]])
b = np.array([[2, 2], [3, 3]])

print('a+b :', np.add(a, b))
print('a-b :', np.subtract(a, b))
print('a*b :', np.multiply(a, b))
print('a/b :', np.divide(a, b))
print('a**b :', np.power(a, b))


a+b : [[ 4  6]
 [12  9]]
a-b : [[0 2]
 [6 3]]
a*b : [[ 4  8]
 [27 18]]
a/b : [[1. 2.]
 [3. 2.]]
a**b : [[  4  16]
 [729 216]]


As *ufuncs* para a aritmética simples contemplam ainda:
+ `absolute(a)` : devolve uma matriz com o módulo dos elementos da matriz `a`,
+ `remainder(a,b)` : devolve uma matriz com o resto da divisão inteira de `a` por `b`,
+ `divmod(a,b)` : devolve duas matrizes matriz com o resultado da divisão inteira de `a` por `b` e o respetivo resto.

Exemplos:

In [56]:
a = np.array([-2, -4, 6, 9])
b = np.array([1, 2, 3, 4])

print('|a| :', np.absolute(a))
print('resto (a/b) :', np.remainder(a, b))
print('a/b e resto de (a/b) :', np.divmod(a, b))


|a| : [2 4 6 9]
resto (a/b) : [0 0 0 1]
a/b e resto de (a/b) : (array([-2, -2,  2,  2]), array([0, 0, 0, 1]))


### Funções trigonométricas

As *ufuncs* contemplam senos, co-senos, tangentes, co-tangentes e as respetivas funções inversas. 

O seguinte exemplo ilustra o seu uso.

In [57]:
ang_rad = np.pi * np.array([0, 1/4, 1/2, 3/4])
print('Ângulo (rad)  :', ang_rad)
y = np.sin(ang_rad)
print('Seno do ângulo:', y)


Ângulo (rad)  : [0.         0.78539816 1.57079633 2.35619449]
Seno do ângulo: [0.         0.70710678 1.         0.70710678]


### Logaritmos

Os logaritmos sobre matrizes estão implementados nas base 2, *e* (neper) e 10. Por exemplo,

In [58]:
f = np.array([1, 10, 100, 1000, 10000])
print('Logaritmo de f:', np.log10(f))


Logaritmo de f: [0. 1. 2. 3. 4.]


### Diferenças: `diff`

Esta *ufunc* implementa diferenças discretas ou seja produz uma matriz cujos elementos resultam da subtração de dois elementos consecutivos. É bastante relevante na implementação numérica de derivadas de funções. Exemplo,

In [59]:
f = np.arange(1, 10)**2       # f(x)   = x**2
derivada_1 = np.diff(f)      # f'(x)  = 2 x
derivada_2 = np.diff(f, n=2)  # f''(x) = 2

print('f  :', f)
print('f\' :', derivada_1)
print('f\'\':', derivada_2)


f  : [ 1  4  9 16 25 36 49 64 81]
f' : [ 3  5  7  9 11 13 15 17]
f'': [2 2 2 2 2 2 2]


### Somas: `sum` e `cumsum`

`sum` implementa a soma de todos os elementos de uma matriz enquanto que `cumsum` devolve uma matriz com a soma cumulativa dos seus elementos. Estas funções podem ser relevantes na implementação numérica de integrais de funções. 

Exemplos:

In [60]:
a = np.arange(1, 10)
print('Soma total :', np.sum(a))
print('Soma cumulativa:', np.cumsum(a))


Soma total : 45
Soma cumulativa: [ 1  3  6 10 15 21 28 36 45]


## Geração de números aleatórios

A biblioteca *numpy* inclui o método `random` que disponibiliza vários métodos para gerar números aleatórios de acordo com várias distribuições de probabilidade. 

Consideramos as distribuições de probabilidade Uniforme, Gaussiana e de Poisson.

### Distribuição Uniforme

O método `randint(low, high, size)` devolve um vector (ou matriz) definida por *size* com números aleatórios inteiros compreendidos entre *low* e *high* de acordo com a distribuição de probabilidade Uniforme.

Por exemplo:

In [61]:
n = np.random.randint(50, 100, 10)

print(n)


[75 67 60 71 93 78 95 84 65 80]


In [62]:
type(n)


numpy.ndarray

In [63]:
n = np.random.randint(50, 100, (3, 2))

print(n)


[[83 57]
 [69 53]
 [76 79]]


O método `uniform(low, high, size)` devolve um vector (ou matriz) definida por `size` com números aleatórios compreendidos entre `low` e `high` de acordo com a distribuição de probabilidade Uniforme. 

Uma das diferenças em relação ao método anterior é que este último devolve número reais (`float`). Por exemplo,

In [64]:
x = np.random.uniform(50, 100, [3, 2])

print(x)


[[62.91358172 79.45701716]
 [67.26637383 81.95344531]
 [73.71019661 79.27635738]]


### Distribuição Normal (Gaussiana)

O método `normal(loc, scale , size)` devolve um vetor (ou matriz) definida por `size` com números aleatórios de acordo com a distribuição de probabilidade Gaussiana de média igual a `loc` e desvio padrão igual a `scale`. 

Por exemplo:

In [65]:
x = np.random.normal(loc=10, scale=2, size=(2, 3))

print(x)


[[10.27727409 10.08297747  8.29815673]
 [ 8.22804849  9.08303145  7.01353613]]


### Distribuição de Poisson

O método `poisson(lam, size)` devolve um vetor (ou matriz) definida por `size` com números aleatórios de acordo com a distribuição de probabilidade de Poisson com um número previsto de eventos igual a `lam`. 

Por exemplo:

In [66]:
x = np.random.poisson(lam=3, size=(2, 3))

print(x)


[[3 0 0]
 [3 5 2]]


## Resumo

Neste capítulo abordámos as funcionalidades principais da biblioteca *NumPy* no que diz respeito à criação e manipulação de matrizes, o cálculo matricial, a aplicação das funções *ufunc* e a geração de números aleatórios de acordo com as distribuições de probabilidade Uniforme, Gaussiana e de Poisson.

## Exercícios propostos

1. Implemente uma função que determine o número total de elementos de uma matriz sem usar o método `numpy.size`.
1. Implemente a matriz diagonal a partir do tuplo (9, 8, 7, 6, 5).
1. Considere a seguinte matriz,

$$
\left[\begin{array}{ccccc}
3  & 4 &  5 & 12 & 1\\
4  & 2 & -3 & -2 & 0\\
7  & 4 &  2 &  3 & 5 \\
-2 & 3 &  1 &  3 & 9
\end{array}
\right]
$$

Construa uma matriz com os elementos das primeiras três linhas e as duas últimas colunas.
1. Considere a seguinte matriz de três linhas por duas colunas. 

$$
\left[\begin{array}{cc}
 -2 & 0\\
 3 & 5 \\
 3 & 9
\end{array}
\right]
$$

Redimensione a matriz para 2 linhas e 3 colunas.
1. Calcule o determinante da matriz

$$
\left[\begin{array}{cccc}
3  & 4 &  5  & 1\\
4  & 2 & -3  & 0\\
7  & 4 &  2  & 5 \\
-2 & 3 &  1  & 9
\end{array}
\right]
$$
1. Calcule a inversa da matriz do problema anterior.
1. Construa uma matriz com 5 linhas e 5 colunas com valores aleatórios entre -10.0 e 10.0 e que obedeça à distribuição de probabilidade uniforme.
1. Resolva o seguinte sistema de equações

$$
\left\{\begin{array}{ccc}
3 z + 4 y + 5 x &=& 12 \\
4 z + 2 y - 3 x &=& 2 \\
7 z + 4 y + 2 x &=& 3 
\end{array}
\right.
$$

